### ISSUE TITLE
Object Structure 

### ISSUE THREAD

**Issue by lhk2000** [dppalomar/portfolioBacktest#10]
Hi, 

I have access to database returns, fundamentals and estimates. Could you show how to import data into the relevant format for the backtest in a vignette or a file?

**Comment by dppalomar** [comment]
In the current vignette (2022-04-20) there is a section called “Loading Data” that explains how the data is organized. From the date you post the question you were probably using a previous version. Please take a look and if it’s not clear I can rewrite that better for the next release.
