### ISSUE TITLE
Error in plotPerformanceVsParams(bt) : No portfolio found in backtest!

### ISSUE THREAD

**Issue by mark0100** [dppalomar/portfolioBacktest#13]
plotPerformanceVsParams(bt) throws the error: No portfolio found in backtest!

In the code for this function on line 7 (N_portfolios <- length(attr(bt_all_portfolios, "portfolio_index"))) it is looking for an attribute called "portfolio_index" in the backtest object, but there is none.

I am using the portfolioBacktest package which is on CRAN.

**Comment by dppalomar** [comment]
The object `bt` returned by the function `portfoliBacktest()` should contain the attribute: `attr(bt, “portfolio_index”)`. I would need more details on how you create your object `bt`.
