### ISSUE TITLE
Saving state inside portfolio functions 

### ISSUE THREAD

**Issue by mark0100** [dppalomar/portfolioBacktest#14]
It would be a great help if it was possible to save/access state inside portfolio functions, especially  for more complex portfolio functions.

Using the .GlobalEnv with assign() does not seem to work for this purpose, even when setting the paral_datasets parameter.

**Comment by dppalomar** [comment]
Please take a look at the vignette section “Initialization for each backtest” where it is explained how to do this with global variables.
